{
  "hash": "171ec17c2d5989b0695e2c77ecfc8a75",
  "result": {
    "markdown": "---\ntitle: \"Challenge 5 Solution - Airbnb Prices in NYC\"\nauthor: \"Linus Jen\"\ndescription: \"Introduction to Visualization\"\ndate: \"6/13/2023\"\nformat:\n  html:\n    toc: true\n    code-copy: true\n    code-tools: true\n    df-print: paged\ncategories:\n  - challenge_5\n  - air_bnb\n  - Linus Jen\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(here)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Read in data\n\nFor this challenge, we'll be investigating the `AB_NYC_2019.csv` dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(here(\"posts\", \"_data\", \"AB_NYC_2019.csv\"))\n\n# View data\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"id\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"name\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"host_id\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"host_name\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"neighbourhood_group\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"neighbourhood\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"latitude\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"longitude\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"room_type\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"price\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"minimum_nights\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"number_of_reviews\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"last_review\"],\"name\":[13],\"type\":[\"date\"],\"align\":[\"right\"]},{\"label\":[\"reviews_per_month\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"calculated_host_listings_count\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"availability_365\"],\"name\":[16],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2539\",\"2\":\"Clean & quiet apt home by the park\",\"3\":\"2787\",\"4\":\"John\",\"5\":\"Brooklyn\",\"6\":\"Kensington\",\"7\":\"40.64749\",\"8\":\"-73.97237\",\"9\":\"Private room\",\"10\":\"149\",\"11\":\"1\",\"12\":\"9\",\"13\":\"2018-10-19\",\"14\":\"0.21\",\"15\":\"6\",\"16\":\"365\"},{\"1\":\"2595\",\"2\":\"Skylit Midtown Castle\",\"3\":\"2845\",\"4\":\"Jennifer\",\"5\":\"Manhattan\",\"6\":\"Midtown\",\"7\":\"40.75362\",\"8\":\"-73.98377\",\"9\":\"Entire home/apt\",\"10\":\"225\",\"11\":\"1\",\"12\":\"45\",\"13\":\"2019-05-21\",\"14\":\"0.38\",\"15\":\"2\",\"16\":\"355\"},{\"1\":\"3647\",\"2\":\"THE VILLAGE OF HARLEM....NEW YORK !\",\"3\":\"4632\",\"4\":\"Elisabeth\",\"5\":\"Manhattan\",\"6\":\"Harlem\",\"7\":\"40.80902\",\"8\":\"-73.94190\",\"9\":\"Private room\",\"10\":\"150\",\"11\":\"3\",\"12\":\"0\",\"13\":\"<NA>\",\"14\":\"NA\",\"15\":\"1\",\"16\":\"365\"},{\"1\":\"3831\",\"2\":\"Cozy Entire Floor of Brownstone\",\"3\":\"4869\",\"4\":\"LisaRoxanne\",\"5\":\"Brooklyn\",\"6\":\"Clinton Hill\",\"7\":\"40.68514\",\"8\":\"-73.95976\",\"9\":\"Entire home/apt\",\"10\":\"89\",\"11\":\"1\",\"12\":\"270\",\"13\":\"2019-07-05\",\"14\":\"4.64\",\"15\":\"1\",\"16\":\"194\"},{\"1\":\"5022\",\"2\":\"Entire Apt: Spacious Studio/Loft by central park\",\"3\":\"7192\",\"4\":\"Laura\",\"5\":\"Manhattan\",\"6\":\"East Harlem\",\"7\":\"40.79851\",\"8\":\"-73.94399\",\"9\":\"Entire home/apt\",\"10\":\"80\",\"11\":\"10\",\"12\":\"9\",\"13\":\"2018-11-19\",\"14\":\"0.10\",\"15\":\"1\",\"16\":\"0\"},{\"1\":\"5099\",\"2\":\"Large Cozy 1 BR Apartment In Midtown East\",\"3\":\"7322\",\"4\":\"Chris\",\"5\":\"Manhattan\",\"6\":\"Murray Hill\",\"7\":\"40.74767\",\"8\":\"-73.97500\",\"9\":\"Entire home/apt\",\"10\":\"200\",\"11\":\"3\",\"12\":\"74\",\"13\":\"2019-06-22\",\"14\":\"0.59\",\"15\":\"1\",\"16\":\"129\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nglimpse(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 48,895\nColumns: 16\n$ id                             <dbl> 2539, 2595, 3647, 3831, 5022, 5099, 512…\n$ name                           <chr> \"Clean & quiet apt home by the park\", \"…\n$ host_id                        <dbl> 2787, 2845, 4632, 4869, 7192, 7322, 735…\n$ host_name                      <chr> \"John\", \"Jennifer\", \"Elisabeth\", \"LisaR…\n$ neighbourhood_group            <chr> \"Brooklyn\", \"Manhattan\", \"Manhattan\", \"…\n$ neighbourhood                  <chr> \"Kensington\", \"Midtown\", \"Harlem\", \"Cli…\n$ latitude                       <dbl> 40.64749, 40.75362, 40.80902, 40.68514,…\n$ longitude                      <dbl> -73.97237, -73.98377, -73.94190, -73.95…\n$ room_type                      <chr> \"Private room\", \"Entire home/apt\", \"Pri…\n$ price                          <dbl> 149, 225, 150, 89, 80, 200, 60, 79, 79,…\n$ minimum_nights                 <dbl> 1, 1, 3, 1, 10, 3, 45, 2, 2, 1, 5, 2, 4…\n$ number_of_reviews              <dbl> 9, 45, 0, 270, 9, 74, 49, 430, 118, 160…\n$ last_review                    <date> 2018-10-19, 2019-05-21, NA, 2019-07-05…\n$ reviews_per_month              <dbl> 0.21, 0.38, NA, 4.64, 0.10, 0.59, 0.40,…\n$ calculated_host_listings_count <dbl> 6, 2, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 3, …\n$ availability_365               <dbl> 365, 355, 365, 194, 0, 129, 0, 220, 0, …\n```\n:::\n\n```{.r .cell-code}\n# Check NAs\ndata %>% summarise(across(everything(), ~sum(is.na(.))))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"id\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"name\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"host_id\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"host_name\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"neighbourhood_group\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"neighbourhood\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"latitude\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"longitude\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"room_type\"],\"name\":[9],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"price\"],\"name\":[10],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"minimum_nights\"],\"name\":[11],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"number_of_reviews\"],\"name\":[12],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"last_review\"],\"name\":[13],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"reviews_per_month\"],\"name\":[14],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"calculated_host_listings_count\"],\"name\":[15],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"availability_365\"],\"name\":[16],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0\",\"2\":\"16\",\"3\":\"0\",\"4\":\"21\",\"5\":\"0\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"9\":\"0\",\"10\":\"0\",\"11\":\"0\",\"12\":\"0\",\"13\":\"10052\",\"14\":\"10052\",\"15\":\"0\",\"16\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Interesting that there are lots of missing data, let's check how many units have no reviews\ndata %>% filter(number_of_reviews == 0) %>% nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10052\n```\n:::\n:::\n\n\n### Briefly describe the data\n\nOur data seems to already be tidy! Each row represents an Airbnb location, as every location has its own `id`. Other columns include the place's `name`, the `host_id` for the host of the location, the `neighborhood_group` and `neighborhood` the place is located in NYC, the `latitude` and `longitude` for the Airbnb, the `room_type` of the Airbnb, `price` and `minimum_nights` that describe the specifics for booking the location, date of `last_review`, approximate `reviews_per_month`, the `calculated_host_listings_count`, and `availability_365` for the Airbnb for the year. There are 48,895 rows and 16 columns. From the title, this data contains information about Airbnbs in NYC for the 2019 year.\n\nWhile there are some missing data (such as the `name`, `host_name`, `last_review`, and `reviews_per_month`). It's interesting though that the `review` related columns are both missing 10,052 rows, or 20.26% of all observations. This is probably because these units have never been rented out or are new, so customers have not left any reviews yet. My suspicions are supported because 10,052 rows have `number_of_reviews` as 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Only column that needs \"fixing\" is the `room_type` \nunique(data$room_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Private room\"    \"Entire home/apt\" \"Shared room\"    \n```\n:::\n\n```{.r .cell-code}\n# 3 unique values, convert to factors\ndata$room_type <- factor(data$room_type)\n```\n:::\n\n\nThe data came already mostly cleaned, with the right data types. The only change we made was to convert the `room_type`s to be factors rather than strings.\n\n## Univariate Visualizations\n\nI'll create 2 univariate visualizations. They will cover `price` and `availability_365`.\n\n### Airbnb Prices\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary of \nsummary(data$price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0    69.0   106.0   152.7   175.0 10000.0 \n```\n:::\n\n```{.r .cell-code}\n# Notice how most of the prices are under $175, with clear outliers at $10,000/night\n\n# Boxplot\nggplot(data) +\n  geom_boxplot(aes(x = price)) +\n  labs(title=\"Boxplot of nightly prices of Airbnbs in NYC\", x=\"Price per night ($)\", y=\"\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinusJen_challenge5_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Boxplot with limits\nggplot(data) +\n  geom_boxplot(aes(x = price)) +\n  xlim(0, 500) + \n  labs(title=\"Boxplot of nightly prices of Airbnbs in NYC\", x=\"Price per night ($)\", y=\"\") + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinusJen_challenge5_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\nThe distribution of nightly Airbnb prices is clearly skewed right, as the mean is greater than the median, and there are many large outliers for the price per night of each Airbnb in NYC. I chose to use a boxplot instead of a histogram / density plot because I used those plots in the following section. To reduce the scaling of the graphs, I limited the x-axis to be a maximum of 500.\n\n### Airbnb Property Availabilites\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data$availability_365)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0     0.0    45.0   112.8   227.0   365.0 \n```\n:::\n\n```{.r .cell-code}\n# Histogram\npar(mfrow=c(1, 2))\nggplot(data) +\n  geom_histogram(aes(availability_365)) + \n  labs(title=\"Property Availability for Airbnbs in NYC\", x=\"Days Available (out of 365)\", y=\"Number of Properties\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinusJen_challenge5_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Density plot\nggplot(data, aes(availability_365)) +\n  geom_histogram(aes(y = ..density..), alpha=0.5) +\n  geom_density(color=\"blue\") +\n  labs(title=\"Property Availability for Airbnbs in NYC\", x=\"Days Available (out of 365)\", y=\"Number of Properties\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinusJen_challenge5_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\nIn the plots above, we see that a majority of Airbnbs had availabilities for less than 20 days, which makes sense given popular NYC is as a tourist destination. However, it's shocking to see that the number and proportion of Airbnbs that were available without anyone staying there after 200 days is quite large, and this proportion greatly increases after 300 days. Again, this distribution is clearly skewed right. I chose to use a histogram / density plot because it's a quick and easy way to visualize the distribution of days available for the Airbnbs in NYC. This dataset is also clearly skewed right, as a majority of the values are < 100 for the availability.\n\n## Bivariate Visualization(s)\n\nFor the bivariate section, it might be interesting to see how the number of available nights relate back to the cost per night - specifically, does the price of an Airbnb show any correlation with how many nights it's available (IE not filled)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot availability vs. price without any filters\nggplot(data, aes(x=price, y=availability_365)) +\n  geom_point() +\n  geom_smooth() +\n  theme_minimal() +\n  labs(title=\"Availability of NYC Airbnbs vs. Price in 2019\", x=\"Daily Price ($)\", y=\"Availability of Airbnb, out of 365 days\")\n```\n\n::: {.cell-output-display}\n![](LinusJen_challenge5_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Remove where prices > 500\ndata %>% filter(price <= 500) %>%\n  ggplot(data=., aes(x=price, y=availability_365)) +\n  geom_point() +\n  geom_smooth() +\n  labs(title=\"Availability of NYC Airbnbs vs. Price in 2019\", x=\"Daily Price ($)\", y=\"Availability of Airbnb, out of 365 days\", subtitle=\"Removing price outliers (Airbnbs that cost more than $500/night)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](LinusJen_challenge5_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\nFrom the two plots above, it doesn't seem like there is any relationship between price and availability of an Airbnb. The first graph shows the full dataset without any an filtering of outliers, while the second graph removes prices where the nightly price was greater than \\$500. The line is mostly horizontal, and was created using a generalized additive model (gam).\n",
    "supporting": [
      "LinusJen_challenge5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}