{
  "hash": "0dda2a2477c0720c2cff9d9e106435f8",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2 - Hotel Bookings\"\nauthor: \"Linus Jen\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"6/5/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n    df-print: paged\ncategories:\n  - challenge_2\n  - hotel_bookings\n  - Linus Jen\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nFor this challenge, I will look at the `hotel_bookings.csv`. A quick Google search leads us to [*this Kaggle site*](https://www.kaggle.com/datasets/jessemostipak/hotel-booking-demand) that discusses the meaning for each variable in greater detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"_data/hotel_bookings.csv\")\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"hotel\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"is_canceled\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lead_time\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"arrival_date_year\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"arrival_date_month\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"arrival_date_week_number\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"arrival_date_day_of_month\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stays_in_weekend_nights\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"stays_in_week_nights\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"adults\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"children\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"babies\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"meal\"],\"name\":[13],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"country\"],\"name\":[14],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"market_segment\"],\"name\":[15],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"distribution_channel\"],\"name\":[16],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"is_repeated_guest\"],\"name\":[17],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"previous_cancellations\"],\"name\":[18],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"previous_bookings_not_canceled\"],\"name\":[19],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reserved_room_type\"],\"name\":[20],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"assigned_room_type\"],\"name\":[21],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"booking_changes\"],\"name\":[22],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"deposit_type\"],\"name\":[23],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"agent\"],\"name\":[24],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"company\"],\"name\":[25],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"days_in_waiting_list\"],\"name\":[26],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"customer_type\"],\"name\":[27],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"adr\"],\"name\":[28],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"required_car_parking_spaces\"],\"name\":[29],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"total_of_special_requests\"],\"name\":[30],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"reservation_status\"],\"name\":[31],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"reservation_status_date\"],\"name\":[32],\"type\":[\"date\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Resort Hotel\",\"2\":\"0\",\"3\":\"342\",\"4\":\"2015\",\"5\":\"July\",\"6\":\"27\",\"7\":\"1\",\"8\":\"0\",\"9\":\"0\",\"10\":\"2\",\"11\":\"0\",\"12\":\"0\",\"13\":\"BB\",\"14\":\"PRT\",\"15\":\"Direct\",\"16\":\"Direct\",\"17\":\"0\",\"18\":\"0\",\"19\":\"0\",\"20\":\"C\",\"21\":\"C\",\"22\":\"3\",\"23\":\"No Deposit\",\"24\":\"NULL\",\"25\":\"NULL\",\"26\":\"0\",\"27\":\"Transient\",\"28\":\"0\",\"29\":\"0\",\"30\":\"0\",\"31\":\"Check-Out\",\"32\":\"2015-07-01\"},{\"1\":\"Resort Hotel\",\"2\":\"0\",\"3\":\"737\",\"4\":\"2015\",\"5\":\"July\",\"6\":\"27\",\"7\":\"1\",\"8\":\"0\",\"9\":\"0\",\"10\":\"2\",\"11\":\"0\",\"12\":\"0\",\"13\":\"BB\",\"14\":\"PRT\",\"15\":\"Direct\",\"16\":\"Direct\",\"17\":\"0\",\"18\":\"0\",\"19\":\"0\",\"20\":\"C\",\"21\":\"C\",\"22\":\"4\",\"23\":\"No Deposit\",\"24\":\"NULL\",\"25\":\"NULL\",\"26\":\"0\",\"27\":\"Transient\",\"28\":\"0\",\"29\":\"0\",\"30\":\"0\",\"31\":\"Check-Out\",\"32\":\"2015-07-01\"},{\"1\":\"Resort Hotel\",\"2\":\"0\",\"3\":\"7\",\"4\":\"2015\",\"5\":\"July\",\"6\":\"27\",\"7\":\"1\",\"8\":\"0\",\"9\":\"1\",\"10\":\"1\",\"11\":\"0\",\"12\":\"0\",\"13\":\"BB\",\"14\":\"GBR\",\"15\":\"Direct\",\"16\":\"Direct\",\"17\":\"0\",\"18\":\"0\",\"19\":\"0\",\"20\":\"A\",\"21\":\"C\",\"22\":\"0\",\"23\":\"No Deposit\",\"24\":\"NULL\",\"25\":\"NULL\",\"26\":\"0\",\"27\":\"Transient\",\"28\":\"75\",\"29\":\"0\",\"30\":\"0\",\"31\":\"Check-Out\",\"32\":\"2015-07-02\"},{\"1\":\"Resort Hotel\",\"2\":\"0\",\"3\":\"13\",\"4\":\"2015\",\"5\":\"July\",\"6\":\"27\",\"7\":\"1\",\"8\":\"0\",\"9\":\"1\",\"10\":\"1\",\"11\":\"0\",\"12\":\"0\",\"13\":\"BB\",\"14\":\"GBR\",\"15\":\"Corporate\",\"16\":\"Corporate\",\"17\":\"0\",\"18\":\"0\",\"19\":\"0\",\"20\":\"A\",\"21\":\"A\",\"22\":\"0\",\"23\":\"No Deposit\",\"24\":\"304\",\"25\":\"NULL\",\"26\":\"0\",\"27\":\"Transient\",\"28\":\"75\",\"29\":\"0\",\"30\":\"0\",\"31\":\"Check-Out\",\"32\":\"2015-07-02\"},{\"1\":\"Resort Hotel\",\"2\":\"0\",\"3\":\"14\",\"4\":\"2015\",\"5\":\"July\",\"6\":\"27\",\"7\":\"1\",\"8\":\"0\",\"9\":\"2\",\"10\":\"2\",\"11\":\"0\",\"12\":\"0\",\"13\":\"BB\",\"14\":\"GBR\",\"15\":\"Online TA\",\"16\":\"TA/TO\",\"17\":\"0\",\"18\":\"0\",\"19\":\"0\",\"20\":\"A\",\"21\":\"A\",\"22\":\"0\",\"23\":\"No Deposit\",\"24\":\"240\",\"25\":\"NULL\",\"26\":\"0\",\"27\":\"Transient\",\"28\":\"98\",\"29\":\"0\",\"30\":\"1\",\"31\":\"Check-Out\",\"32\":\"2015-07-03\"},{\"1\":\"Resort Hotel\",\"2\":\"0\",\"3\":\"14\",\"4\":\"2015\",\"5\":\"July\",\"6\":\"27\",\"7\":\"1\",\"8\":\"0\",\"9\":\"2\",\"10\":\"2\",\"11\":\"0\",\"12\":\"0\",\"13\":\"BB\",\"14\":\"GBR\",\"15\":\"Online TA\",\"16\":\"TA/TO\",\"17\":\"0\",\"18\":\"0\",\"19\":\"0\",\"20\":\"A\",\"21\":\"A\",\"22\":\"0\",\"23\":\"No Deposit\",\"24\":\"240\",\"25\":\"NULL\",\"26\":\"0\",\"27\":\"Transient\",\"28\":\"98\",\"29\":\"0\",\"30\":\"1\",\"31\":\"Check-Out\",\"32\":\"2015-07-03\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nFrom the link and a quick glance above, this dataset includes booking information for hotels, including the hotel type, if the booking is cancelled, number of days between booking and the arrival date, date of arrival, number of weekend nights booked, etc.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# General summary of data\nglimpse(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 119,390\nColumns: 32\n$ hotel                          <chr> \"Resort Hotel\", \"Resort Hotel\", \"Resort…\n$ is_canceled                    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, …\n$ lead_time                      <dbl> 342, 737, 7, 13, 14, 14, 0, 9, 85, 75, …\n$ arrival_date_year              <dbl> 2015, 2015, 2015, 2015, 2015, 2015, 201…\n$ arrival_date_month             <chr> \"July\", \"July\", \"July\", \"July\", \"July\",…\n$ arrival_date_week_number       <dbl> 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,…\n$ arrival_date_day_of_month      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ stays_in_weekend_nights        <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ stays_in_week_nights           <dbl> 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, …\n$ adults                         <dbl> 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, …\n$ children                       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ babies                         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ meal                           <chr> \"BB\", \"BB\", \"BB\", \"BB\", \"BB\", \"BB\", \"BB…\n$ country                        <chr> \"PRT\", \"PRT\", \"GBR\", \"GBR\", \"GBR\", \"GBR…\n$ market_segment                 <chr> \"Direct\", \"Direct\", \"Direct\", \"Corporat…\n$ distribution_channel           <chr> \"Direct\", \"Direct\", \"Direct\", \"Corporat…\n$ is_repeated_guest              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ previous_cancellations         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ previous_bookings_not_canceled <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ reserved_room_type             <chr> \"C\", \"C\", \"A\", \"A\", \"A\", \"A\", \"C\", \"C\",…\n$ assigned_room_type             <chr> \"C\", \"C\", \"C\", \"A\", \"A\", \"A\", \"C\", \"C\",…\n$ booking_changes                <dbl> 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ deposit_type                   <chr> \"No Deposit\", \"No Deposit\", \"No Deposit…\n$ agent                          <chr> \"NULL\", \"NULL\", \"NULL\", \"304\", \"240\", \"…\n$ company                        <chr> \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\",…\n$ days_in_waiting_list           <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ customer_type                  <chr> \"Transient\", \"Transient\", \"Transient\", …\n$ adr                            <dbl> 0.00, 0.00, 75.00, 75.00, 98.00, 98.00,…\n$ required_car_parking_spaces    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_of_special_requests      <dbl> 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 3, …\n$ reservation_status             <chr> \"Check-Out\", \"Check-Out\", \"Check-Out\", …\n$ reservation_status_date        <date> 2015-07-01, 2015-07-01, 2015-07-02, 20…\n```\n:::\n\n```{.r .cell-code}\n# First, look at dates and number of bookings\ndata %>%\n  mutate(arrival_date_month = factor(arrival_date_month, levels = month.name)) %>%\n  group_by(arrival_date_year, arrival_date_month) %>%\n  summarise(count = n()) %>%\n  arrange(arrival_date_year, arrival_date_month)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"arrival_date_year\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"arrival_date_month\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"count\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2015\",\"2\":\"July\",\"3\":\"2776\"},{\"1\":\"2015\",\"2\":\"August\",\"3\":\"3889\"},{\"1\":\"2015\",\"2\":\"September\",\"3\":\"5114\"},{\"1\":\"2015\",\"2\":\"October\",\"3\":\"4957\"},{\"1\":\"2015\",\"2\":\"November\",\"3\":\"2340\"},{\"1\":\"2015\",\"2\":\"December\",\"3\":\"2920\"},{\"1\":\"2016\",\"2\":\"January\",\"3\":\"2248\"},{\"1\":\"2016\",\"2\":\"February\",\"3\":\"3891\"},{\"1\":\"2016\",\"2\":\"March\",\"3\":\"4824\"},{\"1\":\"2016\",\"2\":\"April\",\"3\":\"5428\"},{\"1\":\"2016\",\"2\":\"May\",\"3\":\"5478\"},{\"1\":\"2016\",\"2\":\"June\",\"3\":\"5292\"},{\"1\":\"2016\",\"2\":\"July\",\"3\":\"4572\"},{\"1\":\"2016\",\"2\":\"August\",\"3\":\"5063\"},{\"1\":\"2016\",\"2\":\"September\",\"3\":\"5394\"},{\"1\":\"2016\",\"2\":\"October\",\"3\":\"6203\"},{\"1\":\"2016\",\"2\":\"November\",\"3\":\"4454\"},{\"1\":\"2016\",\"2\":\"December\",\"3\":\"3860\"},{\"1\":\"2017\",\"2\":\"January\",\"3\":\"3681\"},{\"1\":\"2017\",\"2\":\"February\",\"3\":\"4177\"},{\"1\":\"2017\",\"2\":\"March\",\"3\":\"4970\"},{\"1\":\"2017\",\"2\":\"April\",\"3\":\"5661\"},{\"1\":\"2017\",\"2\":\"May\",\"3\":\"6313\"},{\"1\":\"2017\",\"2\":\"June\",\"3\":\"5647\"},{\"1\":\"2017\",\"2\":\"July\",\"3\":\"5313\"},{\"1\":\"2017\",\"2\":\"August\",\"3\":\"4925\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Next, look at countries\ndata %>%\n  group_by(country) %>%\n  summarise(count = n()) %>%\n  arrange(country)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"count\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"ABW\",\"2\":\"2\"},{\"1\":\"AGO\",\"2\":\"362\"},{\"1\":\"AIA\",\"2\":\"1\"},{\"1\":\"ALB\",\"2\":\"12\"},{\"1\":\"AND\",\"2\":\"7\"},{\"1\":\"ARE\",\"2\":\"51\"},{\"1\":\"ARG\",\"2\":\"214\"},{\"1\":\"ARM\",\"2\":\"8\"},{\"1\":\"ASM\",\"2\":\"1\"},{\"1\":\"ATA\",\"2\":\"2\"},{\"1\":\"ATF\",\"2\":\"1\"},{\"1\":\"AUS\",\"2\":\"426\"},{\"1\":\"AUT\",\"2\":\"1263\"},{\"1\":\"AZE\",\"2\":\"17\"},{\"1\":\"BDI\",\"2\":\"1\"},{\"1\":\"BEL\",\"2\":\"2342\"},{\"1\":\"BEN\",\"2\":\"3\"},{\"1\":\"BFA\",\"2\":\"1\"},{\"1\":\"BGD\",\"2\":\"12\"},{\"1\":\"BGR\",\"2\":\"75\"},{\"1\":\"BHR\",\"2\":\"5\"},{\"1\":\"BHS\",\"2\":\"1\"},{\"1\":\"BIH\",\"2\":\"13\"},{\"1\":\"BLR\",\"2\":\"26\"},{\"1\":\"BOL\",\"2\":\"10\"},{\"1\":\"BRA\",\"2\":\"2224\"},{\"1\":\"BRB\",\"2\":\"4\"},{\"1\":\"BWA\",\"2\":\"1\"},{\"1\":\"CAF\",\"2\":\"5\"},{\"1\":\"CHE\",\"2\":\"1730\"},{\"1\":\"CHL\",\"2\":\"65\"},{\"1\":\"CHN\",\"2\":\"999\"},{\"1\":\"CIV\",\"2\":\"6\"},{\"1\":\"CMR\",\"2\":\"10\"},{\"1\":\"CN\",\"2\":\"1279\"},{\"1\":\"COL\",\"2\":\"71\"},{\"1\":\"COM\",\"2\":\"2\"},{\"1\":\"CPV\",\"2\":\"24\"},{\"1\":\"CRI\",\"2\":\"19\"},{\"1\":\"CUB\",\"2\":\"8\"},{\"1\":\"CYM\",\"2\":\"1\"},{\"1\":\"CYP\",\"2\":\"51\"},{\"1\":\"CZE\",\"2\":\"171\"},{\"1\":\"DEU\",\"2\":\"7287\"},{\"1\":\"DJI\",\"2\":\"1\"},{\"1\":\"DMA\",\"2\":\"1\"},{\"1\":\"DNK\",\"2\":\"435\"},{\"1\":\"DOM\",\"2\":\"14\"},{\"1\":\"DZA\",\"2\":\"103\"},{\"1\":\"ECU\",\"2\":\"27\"},{\"1\":\"EGY\",\"2\":\"32\"},{\"1\":\"ESP\",\"2\":\"8568\"},{\"1\":\"EST\",\"2\":\"83\"},{\"1\":\"ETH\",\"2\":\"3\"},{\"1\":\"FIN\",\"2\":\"447\"},{\"1\":\"FJI\",\"2\":\"1\"},{\"1\":\"FRA\",\"2\":\"10415\"},{\"1\":\"FRO\",\"2\":\"5\"},{\"1\":\"GAB\",\"2\":\"4\"},{\"1\":\"GBR\",\"2\":\"12129\"},{\"1\":\"GEO\",\"2\":\"22\"},{\"1\":\"GGY\",\"2\":\"3\"},{\"1\":\"GHA\",\"2\":\"4\"},{\"1\":\"GIB\",\"2\":\"18\"},{\"1\":\"GLP\",\"2\":\"2\"},{\"1\":\"GNB\",\"2\":\"9\"},{\"1\":\"GRC\",\"2\":\"128\"},{\"1\":\"GTM\",\"2\":\"4\"},{\"1\":\"GUY\",\"2\":\"1\"},{\"1\":\"HKG\",\"2\":\"29\"},{\"1\":\"HND\",\"2\":\"1\"},{\"1\":\"HRV\",\"2\":\"100\"},{\"1\":\"HUN\",\"2\":\"230\"},{\"1\":\"IDN\",\"2\":\"35\"},{\"1\":\"IMN\",\"2\":\"2\"},{\"1\":\"IND\",\"2\":\"152\"},{\"1\":\"IRL\",\"2\":\"3375\"},{\"1\":\"IRN\",\"2\":\"83\"},{\"1\":\"IRQ\",\"2\":\"14\"},{\"1\":\"ISL\",\"2\":\"57\"},{\"1\":\"ISR\",\"2\":\"669\"},{\"1\":\"ITA\",\"2\":\"3766\"},{\"1\":\"JAM\",\"2\":\"6\"},{\"1\":\"JEY\",\"2\":\"8\"},{\"1\":\"JOR\",\"2\":\"21\"},{\"1\":\"JPN\",\"2\":\"197\"},{\"1\":\"KAZ\",\"2\":\"19\"},{\"1\":\"KEN\",\"2\":\"6\"},{\"1\":\"KHM\",\"2\":\"2\"},{\"1\":\"KIR\",\"2\":\"1\"},{\"1\":\"KNA\",\"2\":\"2\"},{\"1\":\"KOR\",\"2\":\"133\"},{\"1\":\"KWT\",\"2\":\"16\"},{\"1\":\"LAO\",\"2\":\"2\"},{\"1\":\"LBN\",\"2\":\"31\"},{\"1\":\"LBY\",\"2\":\"8\"},{\"1\":\"LCA\",\"2\":\"1\"},{\"1\":\"LIE\",\"2\":\"3\"},{\"1\":\"LKA\",\"2\":\"7\"},{\"1\":\"LTU\",\"2\":\"81\"},{\"1\":\"LUX\",\"2\":\"287\"},{\"1\":\"LVA\",\"2\":\"55\"},{\"1\":\"MAC\",\"2\":\"16\"},{\"1\":\"MAR\",\"2\":\"259\"},{\"1\":\"MCO\",\"2\":\"4\"},{\"1\":\"MDG\",\"2\":\"1\"},{\"1\":\"MDV\",\"2\":\"12\"},{\"1\":\"MEX\",\"2\":\"85\"},{\"1\":\"MKD\",\"2\":\"10\"},{\"1\":\"MLI\",\"2\":\"1\"},{\"1\":\"MLT\",\"2\":\"18\"},{\"1\":\"MMR\",\"2\":\"1\"},{\"1\":\"MNE\",\"2\":\"5\"},{\"1\":\"MOZ\",\"2\":\"67\"},{\"1\":\"MRT\",\"2\":\"1\"},{\"1\":\"MUS\",\"2\":\"7\"},{\"1\":\"MWI\",\"2\":\"2\"},{\"1\":\"MYS\",\"2\":\"28\"},{\"1\":\"MYT\",\"2\":\"2\"},{\"1\":\"NAM\",\"2\":\"1\"},{\"1\":\"NCL\",\"2\":\"1\"},{\"1\":\"NGA\",\"2\":\"34\"},{\"1\":\"NIC\",\"2\":\"1\"},{\"1\":\"NLD\",\"2\":\"2104\"},{\"1\":\"NOR\",\"2\":\"607\"},{\"1\":\"NPL\",\"2\":\"1\"},{\"1\":\"NULL\",\"2\":\"488\"},{\"1\":\"NZL\",\"2\":\"74\"},{\"1\":\"OMN\",\"2\":\"18\"},{\"1\":\"PAK\",\"2\":\"14\"},{\"1\":\"PAN\",\"2\":\"9\"},{\"1\":\"PER\",\"2\":\"29\"},{\"1\":\"PHL\",\"2\":\"40\"},{\"1\":\"PLW\",\"2\":\"1\"},{\"1\":\"POL\",\"2\":\"919\"},{\"1\":\"PRI\",\"2\":\"12\"},{\"1\":\"PRT\",\"2\":\"48590\"},{\"1\":\"PRY\",\"2\":\"4\"},{\"1\":\"PYF\",\"2\":\"1\"},{\"1\":\"QAT\",\"2\":\"15\"},{\"1\":\"ROU\",\"2\":\"500\"},{\"1\":\"RUS\",\"2\":\"632\"},{\"1\":\"RWA\",\"2\":\"2\"},{\"1\":\"SAU\",\"2\":\"48\"},{\"1\":\"SDN\",\"2\":\"1\"},{\"1\":\"SEN\",\"2\":\"11\"},{\"1\":\"SGP\",\"2\":\"39\"},{\"1\":\"SLE\",\"2\":\"1\"},{\"1\":\"SLV\",\"2\":\"2\"},{\"1\":\"SMR\",\"2\":\"1\"},{\"1\":\"SRB\",\"2\":\"101\"},{\"1\":\"STP\",\"2\":\"2\"},{\"1\":\"SUR\",\"2\":\"5\"},{\"1\":\"SVK\",\"2\":\"65\"},{\"1\":\"SVN\",\"2\":\"57\"},{\"1\":\"SWE\",\"2\":\"1024\"},{\"1\":\"SYC\",\"2\":\"2\"},{\"1\":\"SYR\",\"2\":\"3\"},{\"1\":\"TGO\",\"2\":\"2\"},{\"1\":\"THA\",\"2\":\"59\"},{\"1\":\"TJK\",\"2\":\"9\"},{\"1\":\"TMP\",\"2\":\"3\"},{\"1\":\"TUN\",\"2\":\"39\"},{\"1\":\"TUR\",\"2\":\"248\"},{\"1\":\"TWN\",\"2\":\"51\"},{\"1\":\"TZA\",\"2\":\"5\"},{\"1\":\"UGA\",\"2\":\"2\"},{\"1\":\"UKR\",\"2\":\"68\"},{\"1\":\"UMI\",\"2\":\"1\"},{\"1\":\"URY\",\"2\":\"32\"},{\"1\":\"USA\",\"2\":\"2097\"},{\"1\":\"UZB\",\"2\":\"4\"},{\"1\":\"VEN\",\"2\":\"26\"},{\"1\":\"VGB\",\"2\":\"1\"},{\"1\":\"VNM\",\"2\":\"8\"},{\"1\":\"ZAF\",\"2\":\"80\"},{\"1\":\"ZMB\",\"2\":\"2\"},{\"1\":\"ZWE\",\"2\":\"4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Check the types of hotels\ndata %>%\n  select(hotel) %>% \n  unique()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"hotel\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"Resort Hotel\"},{\"1\":\"City Hotel\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nFrom the output above, we get a quick overview of the data we're working with. There are 119,390 rows and 32 columns, and they include a mix of dates, categories, and numerical values. This data includes arrival dates between July 2015 and August 2017 for hotels all across the world (though a quick lookthrough shows that there's a bias towards European countries). There are two types of hotels included in the dataset: resort hotels and city hotels. This dataset looks to be useful for people interested in doing analysis for hotel bookings, such as countries with a high number of hotel bookings, number of cancellations per country, the types of customer (parents vs. children ratio, type of customer, etc.) who book hotels, trends between the demographics of the room and popular destinations to visit or likelihood to cancel a visit, or other similar analyses. This would also be helpful for advertising agencies to check what markets or destinations are currently popular, and what regions could be emphasized for marketing purposes. Similarly, more analysis could be done looking at dates that tend to have lots of bookings, or when people start looking to book for popular dates.\n\nBecause of how large the dataset is, I'll reduce the number of variables I do analysis on. Specifically, I'll look at `booking_changes`, `adults`, `children`, `babies`, `stays_in_weekend_nights`, `stays_in_week_nights`, and `adr`, or average daily rate. I'm interested in seeing if adult-only hotel bookings differ compared to those that have children or babies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subset data and look at total # of people\ndata_sub <- data %>%\n  select(adults, children, babies, booking_changes, stays_in_weekend_nights, stays_in_week_nights, adr) \n\n# Fill in NAs for the numeric values with 0\ndata_sub <- data_sub %>% \n  mutate_if(is.numeric, ~replace_na(., 0)) %>%\n  mutate(total_ppl = adults + children + babies,\n         has_kids = ifelse(children + babies == 0, FALSE, TRUE))\n\n\n# First, look at the summaries\nsummary(data_sub)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     adults          children           babies          booking_changes  \n Min.   : 0.000   Min.   : 0.0000   Min.   : 0.000000   Min.   : 0.0000  \n 1st Qu.: 2.000   1st Qu.: 0.0000   1st Qu.: 0.000000   1st Qu.: 0.0000  \n Median : 2.000   Median : 0.0000   Median : 0.000000   Median : 0.0000  \n Mean   : 1.856   Mean   : 0.1039   Mean   : 0.007949   Mean   : 0.2211  \n 3rd Qu.: 2.000   3rd Qu.: 0.0000   3rd Qu.: 0.000000   3rd Qu.: 0.0000  \n Max.   :55.000   Max.   :10.0000   Max.   :10.000000   Max.   :21.0000  \n stays_in_weekend_nights stays_in_week_nights      adr         \n Min.   : 0.0000         Min.   : 0.0         Min.   :  -6.38  \n 1st Qu.: 0.0000         1st Qu.: 1.0         1st Qu.:  69.29  \n Median : 1.0000         Median : 2.0         Median :  94.58  \n Mean   : 0.9276         Mean   : 2.5         Mean   : 101.83  \n 3rd Qu.: 2.0000         3rd Qu.: 3.0         3rd Qu.: 126.00  \n Max.   :19.0000         Max.   :50.0         Max.   :5400.00  \n   total_ppl       has_kids      \n Min.   : 0.000   Mode :logical  \n 1st Qu.: 2.000   FALSE:110058   \n Median : 2.000   TRUE :9332     \n Mean   : 1.968                  \n 3rd Qu.: 2.000                  \n Max.   :55.000                  \n```\n:::\n\n```{.r .cell-code}\n# Find cases where there are many adults\ndata_sub %>%\n  filter(adults >= 5 | children > 2 | babies > 2) %>%\n  select(total_ppl, adults, children, babies) %>%\n  arrange(desc(total_ppl))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"total_ppl\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"adults\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"children\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"babies\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"55\",\"2\":\"55\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"50\",\"2\":\"50\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"40\",\"2\":\"40\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"27\",\"2\":\"27\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"27\",\"2\":\"27\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"26\",\"2\":\"26\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"26\",\"2\":\"26\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"26\",\"2\":\"26\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"26\",\"2\":\"26\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"26\",\"2\":\"26\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"20\",\"2\":\"20\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"20\",\"2\":\"20\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"12\",\"2\":\"2\",\"3\":\"10\",\"4\":\"0\"},{\"1\":\"12\",\"2\":\"2\",\"3\":\"0\",\"4\":\"10\"},{\"1\":\"10\",\"2\":\"10\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"10\",\"2\":\"1\",\"3\":\"0\",\"4\":\"9\"},{\"1\":\"6\",\"2\":\"6\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"5\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"5\",\"3\":\"0\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"5\",\"2\":\"2\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"4\",\"2\":\"1\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"4\",\"2\":\"1\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"4\",\"2\":\"1\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"4\",\"2\":\"1\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"},{\"1\":\"3\",\"2\":\"0\",\"3\":\"3\",\"4\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nFrom our summary above, we see that the number of people tend to be around 0-2 people in total, as the number of adults is around 2, while there are rarely any children and babies in this dataset. It is interesting to note though that we see instances where there are 55 adults, 10 kids, or 10 babies, and from the table above, we can see that when the party is large, it is made up mostly of a large number of only one group (rather than a large group having many adults, kids, and/or babies). Additionally, of all the parties who had a hotel space, almost all of them don't have kids (110058 out of 119390 observations or 0.921836%), making this dataset heavily skewed towards people without children. For the `stays_in_week_nights` and `booking_changes`, the distributions are slightly skewed right, as the means are greater than their respective medians, while `stays_in_weekend_nights` seems to be almost symmetrical. However, all numeric variables clearly have outliers, as evident by a max `adr` of $5400 or `adults` having 55 people.\n\n\n## Provide Grouped Summary Statistics\n\nFor this section, we will now see whether or not bookings with children led to differences in the distributions of the `total_ppl`, `adr`, `booking_changes`, `stays_in_week_nights`, and `stays_in_weekend_nights`. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_sub %>% \n  group_by(has_kids) %>%\n  select(booking_changes, stays_in_weekend_nights, stays_in_week_nights, adr, total_ppl) %>%\n  rename(c(bookingChanges = booking_changes, staysInWeekendNights = stays_in_weekend_nights, staysInWeekNights = stays_in_week_nights, totalPpl = total_ppl, hasKids = has_kids)) %>% \n  summarise(across(everything(), list(sd = sd, min = min, quant1 = ~quantile(., 0.25), mean = mean, median = median, quant3 = ~quantile(., 0.75), max = max))) %>%\n  pivot_longer(contains(\"_\"), names_to = c(\"colNames\", \".value\"), names_sep = \"_\") %>%\n  arrange(colNames, hasKids)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"hasKids\"],\"name\":[1],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"colNames\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"sd\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"min\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"quant1\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mean\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"median\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"quant3\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"max\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"FALSE\",\"2\":\"adr\",\"3\":\"46.5133530\",\"4\":\"-6.38\",\"5\":\"67\",\"6\":\"97.3707770\",\"7\":\"90.8\",\"8\":\"120\",\"9\":\"5400.0\"},{\"1\":\"TRUE\",\"2\":\"adr\",\"3\":\"64.4703364\",\"4\":\"0.00\",\"5\":\"109\",\"6\":\"154.4347000\",\"7\":\"148.5\",\"8\":\"195\",\"9\":\"451.5\"},{\"1\":\"FALSE\",\"2\":\"bookingChanges\",\"3\":\"0.6308228\",\"4\":\"0.00\",\"5\":\"0\",\"6\":\"0.2059732\",\"7\":\"0.0\",\"8\":\"0\",\"9\":\"21.0\"},{\"1\":\"TRUE\",\"2\":\"bookingChanges\",\"3\":\"0.8461883\",\"4\":\"0.00\",\"5\":\"0\",\"6\":\"0.3998071\",\"7\":\"0.0\",\"8\":\"1\",\"9\":\"17.0\"},{\"1\":\"FALSE\",\"2\":\"staysInWeekNights\",\"3\":\"1.9056086\",\"4\":\"0.00\",\"5\":\"1\",\"6\":\"2.4724327\",\"7\":\"2.0\",\"8\":\"3\",\"9\":\"50.0\"},{\"1\":\"TRUE\",\"2\":\"staysInWeekNights\",\"3\":\"1.9092318\",\"4\":\"0.00\",\"5\":\"1\",\"6\":\"2.8289756\",\"7\":\"3.0\",\"8\":\"4\",\"9\":\"22.0\"},{\"1\":\"FALSE\",\"2\":\"staysInWeekendNights\",\"3\":\"0.9972856\",\"4\":\"0.00\",\"5\":\"0\",\"6\":\"0.9124462\",\"7\":\"1.0\",\"8\":\"2\",\"9\":\"19.0\"},{\"1\":\"TRUE\",\"2\":\"staysInWeekendNights\",\"3\":\"0.9969705\",\"4\":\"0.00\",\"5\":\"0\",\"6\":\"1.1063009\",\"7\":\"1.0\",\"8\":\"2\",\"9\":\"8.0\"},{\"1\":\"FALSE\",\"2\":\"totalPpl\",\"3\":\"0.5881471\",\"4\":\"0.00\",\"5\":\"2\",\"6\":\"1.8474441\",\"7\":\"2.0\",\"8\":\"2\",\"9\":\"55.0\"},{\"1\":\"TRUE\",\"2\":\"totalPpl\",\"3\":\"0.6286690\",\"4\":\"1.00\",\"5\":\"3\",\"6\":\"3.3928418\",\"7\":\"3.0\",\"8\":\"4\",\"9\":\"12.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe table above shows some comparisons between parties with and without children. Firstly, we see that parties with children tend to have more people in the reservation than those that are adult only. This makes sense, as having group trips for adults tends to be rare (in my opinion). This finding also can impact `adr`, as we see that the average daily rate is actually higher for parties with children than with children. This might be due to hotels charging more for children or because larger parties require more beds or space, thus increasing the average daily rate for these stays. We also see that groups with children tend to have a greater number of booking changes, and this can be explained by how kids tend to have unexpected and changing schedules that might impact travel plans (such as getting sick). We also see that parties with children tend to have longer stays during both the weekends and weekdays, but this could be attributed to how school breaks tend to be for longer periods of time (such as spring break being 1+ weeks long, or summer and winter breaks being multi-week, if not multi-month, respites). However, statistical analyses need to be run to ensure that these hypotheses are statistically significant, and because this data is heavily skewed towards people without children, more data should be collected to get a better sample with a closer proportion of people with and without kids.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}