{
  "hash": "eb12c45668fcfada04e0938643b2fe01",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1 Solution - Railroad Employment\"\nauthor: \"Linus Jen\"\ndescription: \"Reading in data and creating a post for US State/County Railroad Employment Data in 2012\"\ndate: \"5/30/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n    df-print: paged\ncategories:\n  - challenge_1\n  - railroads\n  - faostat\n  - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nFor this homework, I decided to look at the `StateCounty2012.xls` dataset. I opened the file and noticed that the first three rows are part of the header, so I skipped those lines using the `skip` argument in the `read_xls()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import data\ndata <- read_xls(\"_data/StateCounty2012.xls\", skip=3)\n```\n:::\n\n### Data preprocessing\n\nTo ensure that the data was properly loaded in, I also looked at the top 10 rows of the dataset. I also noticed that there were only 3 columns in the `.xls` file, but 5 columns in our loaded dataset. To explore further, I applied the `is.na()` function to all columns, suspecting that the second and fourth columns were loaded improperly and were fully blank. After confirming this, I removed those columns from the dataset. Lastly, I noticed that there were some totals included in our rows, and these occurred when the `COUNTY` value was empty. We need to be mindful not to remove CANADA though as an observation, even though it doesn't have a `COUNTY` value!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check head\nprint(head(data, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 5\n   STATE     ...2  COUNTY               ...4  TOTAL\n   <chr>     <lgl> <chr>                <lgl> <dbl>\n 1 AE        NA    APO                  NA        2\n 2 AE Total1 NA    <NA>                 NA        2\n 3 AK        NA    ANCHORAGE            NA        7\n 4 AK        NA    FAIRBANKS NORTH STAR NA        2\n 5 AK        NA    JUNEAU               NA        3\n 6 AK        NA    MATANUSKA-SUSITNA    NA        2\n 7 AK        NA    SITKA                NA        1\n 8 AK        NA    SKAGWAY MUNICIPALITY NA       88\n 9 AK Total  NA    <NA>                 NA      103\n10 AL        NA    AUTAUGA              NA      102\n```\n:::\n\n```{.r .cell-code}\n# Find dimensions\nprint(dim(data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2990    5\n```\n:::\n\n```{.r .cell-code}\n# Check if columns are completely blank\nsapply(data, function(x) all(is.na(x)))  # We see that columns 2 and 4 are empty!\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n STATE   ...2 COUNTY   ...4  TOTAL \n FALSE   TRUE  FALSE   TRUE  FALSE \n```\n:::\n\n```{.r .cell-code}\n# Check where `COUNTY` is blank\ndata %>% filter(is.na(COUNTY))  # Notice that when `COUNTY` is empty, values are totals are not important\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"STATE\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"...2\"],\"name\":[2],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"COUNTY\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"...4\"],\"name\":[4],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"TOTAL\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"AE Total1\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2\"},{\"1\":\"AK Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"103\"},{\"1\":\"AL Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"4257\"},{\"1\":\"AP Total1\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"1\"},{\"1\":\"AR Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3871\"},{\"1\":\"AZ Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3153\"},{\"1\":\"CA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"13137\"},{\"1\":\"CO Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3650\"},{\"1\":\"CT Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2592\"},{\"1\":\"DC Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"279\"},{\"1\":\"DE Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"1495\"},{\"1\":\"FL Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"7419\"},{\"1\":\"GA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"8605\"},{\"1\":\"HI Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"4\"},{\"1\":\"IA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"4019\"},{\"1\":\"ID Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"1563\"},{\"1\":\"IL Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"19131\"},{\"1\":\"IN Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"8537\"},{\"1\":\"KS Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"6092\"},{\"1\":\"KY Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"4811\"},{\"1\":\"LA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3915\"},{\"1\":\"MA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3379\"},{\"1\":\"MD Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"4709\"},{\"1\":\"ME Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"654\"},{\"1\":\"MI Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3932\"},{\"1\":\"MN Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"5467\"},{\"1\":\"MO Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"8419\"},{\"1\":\"MS Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2111\"},{\"1\":\"MT Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3327\"},{\"1\":\"NC Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3143\"},{\"1\":\"ND Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2204\"},{\"1\":\"NE Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"13176\"},{\"1\":\"NH Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"393\"},{\"1\":\"NJ Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"8329\"},{\"1\":\"NM Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"1958\"},{\"1\":\"NV Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"746\"},{\"1\":\"NY Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"17050\"},{\"1\":\"OH Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"9056\"},{\"1\":\"OK Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2318\"},{\"1\":\"OR Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2322\"},{\"1\":\"PA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"12769\"},{\"1\":\"RI Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"487\"},{\"1\":\"SC Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2296\"},{\"1\":\"SD Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"949\"},{\"1\":\"TN Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"4952\"},{\"1\":\"TX Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"19839\"},{\"1\":\"UT Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"1917\"},{\"1\":\"VA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"7551\"},{\"1\":\"VT Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"259\"},{\"1\":\"WA Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"5222\"},{\"1\":\"WI Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3773\"},{\"1\":\"WV Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"3213\"},{\"1\":\"WY Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"2876\"},{\"1\":\"Grand Total\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"255432\"},{\"1\":\"NA\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\"},{\"1\":\"CANADA\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"662\"},{\"1\":\"NA\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\"},{\"1\":\"1  Military designation.\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\"},{\"1\":\"NA\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\"},{\"1\":\"NOTE:  Excludes 2,896 employees without an address.\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"5\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThus, the following chunk of code cleans our dataset to only have US states, counties, and the total railroad employment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove the 2 columns and when `COUNTY` is empty\ndata_clean <- data %>%\n  select(\"STATE\", \"COUNTY\", \"TOTAL\") %>%\n  filter(!is.na(COUNTY) | (STATE == \"CANADA\"))\n\n# Check dimensions\ndim(data_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2931    3\n```\n:::\n:::\n\n\n## Describe the data\n\n### Overview / Summary\n\nFrom the Excel file title, this dataset represents the total railroad employment by state and county for 2012. This data is on a county level, and most likely counts the number of railroad employees for each county, with summations for each state also included in the original `.xls` file (though it was removed for this dataset). This data might prove valuable if combined with other datasets, such as seeing how the employment per county or state might change over time (if historical data was gathered), checking for relationships being railroad tracks built or existing in each county and the number of employees in 2012 (if data was collected about the railroad track mileage itself), or how railroad employment per county relates back to state statistics, such as population, land size of the state, or unemployment rates of the state (assuming this data is gathered).\n\nFrom the findings below, we see that there are a total of 256,094 reported railroad employees in 2012. There are a total of 54 unique \"counties\" that include 2 US territories, Canada, and the District of Columbia. Overall, there seems to be a skew in the distribution of where the railroad employees are, though further geographical analysis needs to be done to make any concrete assumptions.\n\n### Data Exploration\n\nThis section will provide a deeper dive into the data, and the exact commands used to get the information for the introduction and overview section above.\n\nFirst, let's look at the head of the data and the various data types.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quick glance of data\nhead(data_clean, 10)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"STATE\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"COUNTY\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"TOTAL\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"AE\",\"2\":\"APO\",\"3\":\"2\"},{\"1\":\"AK\",\"2\":\"ANCHORAGE\",\"3\":\"7\"},{\"1\":\"AK\",\"2\":\"FAIRBANKS NORTH STAR\",\"3\":\"2\"},{\"1\":\"AK\",\"2\":\"JUNEAU\",\"3\":\"3\"},{\"1\":\"AK\",\"2\":\"MATANUSKA-SUSITNA\",\"3\":\"2\"},{\"1\":\"AK\",\"2\":\"SITKA\",\"3\":\"1\"},{\"1\":\"AK\",\"2\":\"SKAGWAY MUNICIPALITY\",\"3\":\"88\"},{\"1\":\"AL\",\"2\":\"AUTAUGA\",\"3\":\"102\"},{\"1\":\"AL\",\"2\":\"BALDWIN\",\"3\":\"143\"},{\"1\":\"AL\",\"2\":\"BARBOUR\",\"3\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nglimpse(data_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 2,931\nColumns: 3\n$ STATE  <chr> \"AE\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AK\", \"AL\", \"AL\", \"AL\", \"AL…\n$ COUNTY <chr> \"APO\", \"ANCHORAGE\", \"FAIRBANKS NORTH STAR\", \"JUNEAU\", \"MATANUSK…\n$ TOTAL  <dbl> 2, 7, 2, 3, 2, 1, 88, 102, 143, 1, 25, 154, 13, 29, 45, 13, 9, …\n```\n:::\n\n```{.r .cell-code}\n# Check for missingness\ncolSums(is.na(data_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n STATE COUNTY  TOTAL \n     0      1      0 \n```\n:::\n\n```{.r .cell-code}\n# Lastly, check for total number of railroad employees reported\nsum(data_clean$TOTAL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 256094\n```\n:::\n:::\n\nFrom the output above, we see that there are 2,931 observations (rows) with 3 columns of the state name, the county name, and the total number of people employed in that county/state combination. Additionally, we see that there is 1 missing value for the `COUNTY` column, which is a result of all people employed in Canada being aggregated into one row. Lastly, there were a total of 256,094 total reported railroad employees in 2012.\n\nNext, let's look at what states are included in our dataset and the number of counties make up each state. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of states included in dataset\nprint(paste0(\"Number of unique states: \", length(unique(data_clean$STATE))))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Number of unique states: 54\"\n```\n:::\n\n```{.r .cell-code}\n# Check if there are counties with no employes\ndata_clean %>% \n  filter(TOTAL == 0) %>%\n  dim()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0 3\n```\n:::\n\n```{.r .cell-code}\n# Check number of counties per state\nnum_counties <- table(data_clean$STATE)\nprint(\"Number of counties \")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Number of counties \"\n```\n:::\n\n```{.r .cell-code}\nnum_counties[order(num_counties, decreasing=TRUE)]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    TX     GA     KY     MO     IL     IA     KS     NC     IN     VA     TN \n   221    152    119    115    103     99     95     94     92     92     91 \n    NE     OH     MN     MI     MS     OK     AR     WI     AL     FL     PA \n    89     88     86     78     78     73     72     69     67     67     65 \n    LA     NY     CO     CA     MT     WV     SD     ND     SC     WA     ID \n    63     61     57     55     53     53     52     49     46     39     36 \n    OR     NM     UT     MD     WY     NJ     ME     AZ     VT     MA     NV \n    33     29     25     24     22     21     16     15     14     12     12 \n    NH     CT     AK     RI     DE     HI     AE     AP CANADA     DC \n    10      8      6      5      3      3      1      1      1      1 \n```\n:::\n:::\n\nIn the print statement, we see that there are 54 unique \"states\". Upon further analysis, we see that this is because Canada is counted as a state in addition to the 50 US states, and several US territories and the US capital are included: \"AE\" is the armed forces Africa, \"AP\" is the armed forces in the Pacific, and DC is the District of Columbia. Additionally, we see that ONLY counties with railroad employees are included in this list, so we cannot assume that all counties are included in this dataset.\n\nFrom our table, We see that Texas, Georgia, and Kentucky are the top three states that have the most counties with railroad employees.\n\nNext, we'll look at the railroad employment for each state.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_agg <- data_clean %>% \n  group_by(STATE) %>%\n  summarise(total_employment = sum(TOTAL)) %>%\n  arrange(desc(total_employment))\nstate_agg\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"STATE\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"total_employment\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"TX\",\"2\":\"19839\"},{\"1\":\"IL\",\"2\":\"19131\"},{\"1\":\"NY\",\"2\":\"17050\"},{\"1\":\"NE\",\"2\":\"13176\"},{\"1\":\"CA\",\"2\":\"13137\"},{\"1\":\"PA\",\"2\":\"12769\"},{\"1\":\"OH\",\"2\":\"9056\"},{\"1\":\"GA\",\"2\":\"8605\"},{\"1\":\"IN\",\"2\":\"8537\"},{\"1\":\"MO\",\"2\":\"8419\"},{\"1\":\"NJ\",\"2\":\"8329\"},{\"1\":\"VA\",\"2\":\"7551\"},{\"1\":\"FL\",\"2\":\"7419\"},{\"1\":\"KS\",\"2\":\"6092\"},{\"1\":\"MN\",\"2\":\"5467\"},{\"1\":\"WA\",\"2\":\"5222\"},{\"1\":\"TN\",\"2\":\"4952\"},{\"1\":\"KY\",\"2\":\"4811\"},{\"1\":\"MD\",\"2\":\"4709\"},{\"1\":\"AL\",\"2\":\"4257\"},{\"1\":\"IA\",\"2\":\"4019\"},{\"1\":\"MI\",\"2\":\"3932\"},{\"1\":\"LA\",\"2\":\"3915\"},{\"1\":\"AR\",\"2\":\"3871\"},{\"1\":\"WI\",\"2\":\"3773\"},{\"1\":\"CO\",\"2\":\"3650\"},{\"1\":\"MA\",\"2\":\"3379\"},{\"1\":\"MT\",\"2\":\"3327\"},{\"1\":\"WV\",\"2\":\"3213\"},{\"1\":\"AZ\",\"2\":\"3153\"},{\"1\":\"NC\",\"2\":\"3143\"},{\"1\":\"WY\",\"2\":\"2876\"},{\"1\":\"CT\",\"2\":\"2592\"},{\"1\":\"OR\",\"2\":\"2322\"},{\"1\":\"OK\",\"2\":\"2318\"},{\"1\":\"SC\",\"2\":\"2296\"},{\"1\":\"ND\",\"2\":\"2204\"},{\"1\":\"MS\",\"2\":\"2111\"},{\"1\":\"NM\",\"2\":\"1958\"},{\"1\":\"UT\",\"2\":\"1917\"},{\"1\":\"ID\",\"2\":\"1563\"},{\"1\":\"DE\",\"2\":\"1495\"},{\"1\":\"SD\",\"2\":\"949\"},{\"1\":\"NV\",\"2\":\"746\"},{\"1\":\"CANADA\",\"2\":\"662\"},{\"1\":\"ME\",\"2\":\"654\"},{\"1\":\"RI\",\"2\":\"487\"},{\"1\":\"NH\",\"2\":\"393\"},{\"1\":\"DC\",\"2\":\"279\"},{\"1\":\"VT\",\"2\":\"259\"},{\"1\":\"AK\",\"2\":\"103\"},{\"1\":\"HI\",\"2\":\"4\"},{\"1\":\"AE\",\"2\":\"2\"},{\"1\":\"AP\",\"2\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nFrom the table above, we see that Texas, Illinois, and New York make up the top three states with the most people employed working on railroads, while Hawaii, army forces in Africa, and army forces in the Pacific make up the states with the least number of railroad employees. This isn't shocking. One hypothesis could be that many of the larger and more central states have more railroad employees. This is probably because products need to move across the country, so these states need more railroad tracks (and thus employees to build and maintain these tracks) for goods to move across the country.\n\nLastly, we'll look at a simple distribution of the employee data across counties and states.\n\n::: {.cell}\n\n```{.r .cell-code}\n# 5 number summary for county level\nsummary(data_clean$TOTAL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00    7.00   21.00   87.37   65.00 8207.00 \n```\n:::\n\n```{.r .cell-code}\n# 5 number summary for state level\nsummary(state_agg$total_employment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      1    1652    3353    4742    5936   19839 \n```\n:::\n:::\n\nOn the county level, the data is clearly skewed right, as the median of 21 is far below the mean of 87.37. We see that there's a max of 8,207 railroad employees in one country, which is pretty large. However, there's also a fair amount of  counties with very little employees, as about 25% of counties have 7 or less railroad employees.\n\nOn the state level, the numbers are far greater for number of railroad employees. The distribution is still skewed right, with the mean of 3,353 still being less than the mean of 4,742. There's a minimum of 1 railroad employee in a state, and a maximum of 19,839 railroad employees (in Texas, as seen in the previous table / code chunk).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}